version: "2"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
  influxdb:
    image: influxdb
    container_name: influxdb
    environment:
      - INFLUXDB_DB=mydb
  ntpinflux:
    container_name: ntpinfluxdb
    build: ntp-influxdb
    command: ["python", "-u", "./ntp-influxdb.py", "pool.ntp.org", "influxdb", "8086"]
